// This file was generated with Diez - https://diez.org
// Do not edit this file directly.

package org.diez.stdlibTestStub

data class Bindings(
    val image: Image = Image(File("assets/image%20with%20spaces.jpg", "image"), File("assets/image%20with%20spaces@2x.jpg", "image"), File("assets/image%20with%20spaces@3x.jpg", "image"), File("assets/image%20with%20spaces@4x.jpg", "image"), Size2D(246f, 246f)),
    val lottie: Lottie = Lottie(File("assets/lottie.json", "raw"), true, true),
    val typograph: Typograph = Typograph(Font(File("assets/SomeFont.ttf", "font"), "SomeFont"), 50f, Color(0.16666666666666666f, 1f, 0.5f, 1f), false),
    val linearGradient: LinearGradient = LinearGradient(arrayOf<GradientStop>(GradientStop(0f, Color(0f, 1f, 0.5f, 1f)), GradientStop(1f, Color(0.6666666666666666f, 1f, 0.5f, 1f))), Point2D(0f, 0.5f), Point2D(1f, 0.5f)),
    val point: Point2D = Point2D(0.5f, 0.5f),
    val size: Size2D = Size2D(400f, 300f),
    val shadow: DropShadow = DropShadow(Point2D(1f, 2f), 3f, Color(0.3333333333333333f, 1f, 0.5f, 0.5f)),
    val fill: Fill = Fill(Color(0f, 1f, 0.5f, 1f), LinearGradient(arrayOf<GradientStop>(GradientStop(0f, Color(0f, 0f, 0f, 1f)), GradientStop(1f, Color(0f, 0f, 1f, 1f))), Point2D(0f, 0f), Point2D(1f, 1f)), "Color"),
    val panel: Panel = Panel(5f, Fill(Color(0.6666666666666666f, 1f, 0.5f, 1f), LinearGradient(arrayOf<GradientStop>(GradientStop(0f, Color(0f, 0f, 0f, 1f)), GradientStop(1f, Color(0f, 0f, 1f, 1f))), Point2D(0f, 0f), Point2D(1f, 1f)), "Color"), 6f),
    val color: Color = Color(0f, 0f, 0f, 1f),
    val file: File = File("assets/SomeFile.txt", "raw")
) : RootComponent {
    companion object {}
    override val name = "Bindings"
}
