// This file was generated with Diez - https://diez.org
// Do not edit this file directly.

package org.diez.stdlibTestStub

/**
  Provides a drop shadow.
*/
data class DropShadow(
    /**
      DropShadow data.
    */
    val offset: Point2D,
    /**
      DropShadow data.
    */
    val radius: Float,
    /**
      DropShadow data.
    */
    val color: Color
) {
    companion object {}
}
