// This file was generated with Diez - https://diez.org
// Do not edit this file directly.

package org.diez.stdlibTestStub

/**
 * Provides a drop shadow.
 *
 */
data class DropShadow(
    /**
     * DropShadow data.
     *
     * [1, 2]
     */
    val offset: Point2D,
    /**
     * DropShadow data.
     *
     */
    val radius: Float,
    /**
     * DropShadow data.
     *
     * hsla(0.33, 1, 0.5, 0.5)
     */
    val color: Color
) {
    companion object {}
}
