// This file was generated with Diez - https://diez.org
// Do not edit this file directly.

package org.diez.stdlibTestStub

/**
  A representation of a font resource, with a reference to a [[File]] containing a TTF or OTF font file.
**/
data class Font(
    /**
      Font data.
    **/
    val file: File,
    /**
      Font data.
    **/
    val name: String
) {
    companion object {}
}
