// This file was generated with Diez - https://diez.org
// Do not edit this file directly.

package org.diez.stdlibTestStub

/**
 * Provides a gradient stop.
 *
 */
data class GradientStop(
    /**
     * GradientStop data.
     *
     * 1
     */
    val position: Float,
    /**
     * GradientStop data.
     *
     * hsla(0.67, 1, 0.5, 1)
     */
    val color: Color
) {
    companion object {}
}
