// This file was generated with Diez - https://diez.org
// Do not edit this file directly.

package org.diez.stdlibTestStub

/**
  Provides a gradient stop.
*/
data class GradientStop(
    /**
      GradientStop data.
    */
    val position: Float,
    /**
      GradientStop data.
    */
    val color: Color
) {
    companion object {}
}
