// This file was generated with Diez - https://diez.org
// Do not edit this file directly.

package org.diez.stdlibTestStub

/**
 * Provides a two dimensional size.
 * 
 * Usage: `size = Size2D.make(1920, 1080);`.
 *
 */
data class Size2D(
    /**
     * Size data.
     *
     * 246
     */
    val width: Float,
    /**
     * Size data.
     *
     * 246
     */
    val height: Float
) {
    companion object {}
}
