// This file was generated with Diez - https://diez.org
// Do not edit this file directly.

import Foundation
import CoreGraphics
@objc(DEZDropShadow)
public final class DropShadow: NSObject, Decodable {
    /**
     * DropShadow data.
     *
     * [1, 2]
     */
    @objc public internal(set) var offset: Point2D
    /**
     * DropShadow data.
     *
     */
    @objc public internal(set) var radius: CGFloat
    /**
     * DropShadow data.
     *
     * hsla(0.33, 1, 0.5, 0.5)
     */
    @objc public internal(set) var color: Color

    init(
        offset: Point2D,
        radius: CGFloat,
        color: Color
    ) {
        self.offset = offset
        self.radius = radius
        self.color = color
    }
}

extension DropShadow: ReflectedCustomStringConvertible {
    public override var description: String {
        return reflectedDescription
    }
}
