// This file was generated with Diez - https://diez.org
// Do not edit this file directly.

import Foundation
import CoreGraphics
@objc(DEZLottie)
public final class Lottie: NSObject, Decodable {
    /**
     * Lottie data.
     *
     * assets/lottie.json
     */
    @objc public internal(set) var file: File
    /**
     * Lottie data.
     *
     * true
     */
    @objc public internal(set) var loop: Bool
    /**
     * Lottie data.
     *
     * true
     */
    @objc public internal(set) var autoplay: Bool

    init(
        file: File,
        loop: Bool,
        autoplay: Bool
    ) {
        self.file = file
        self.loop = loop
        self.autoplay = autoplay
    }
}

extension Lottie: ReflectedCustomStringConvertible {
    public override var description: String {
        return reflectedDescription
    }
}
