// This file was generated with Diez - https://diez.org
// Do not edit this file directly.

import Foundation
import CoreGraphics
@objc(DEZPoint2D)
public final class Point2D: NSObject, Decodable {
    /**
     * Point data.
     *
     */
    @objc public internal(set) var x: CGFloat
    /**
     * Point data.
     *
     */
    @objc public internal(set) var y: CGFloat

    init(
        x: CGFloat,
        y: CGFloat
    ) {
        self.x = x
        self.y = y
    }
}

extension Point2D: ReflectedCustomStringConvertible {
    public override var description: String {
        return reflectedDescription
    }
}
