// This file was generated with Diez - https://diez.org
// Do not edit this file directly.

import Foundation
import CoreGraphics

@objc(DEZTypograph)
public final class Typograph: NSObject, Decodable {
    @objc public internal(set) var font: Font
    @objc public internal(set) var fontSize: CGFloat
    @objc public internal(set) var color: Color
    @objc public internal(set) var iosTextStyle: String
    @objc public internal(set) var shouldScale: Bool
    @objc public internal(set) var lineHeight: CGFloat
    @objc public internal(set) var letterSpacing: CGFloat

    init(
        font: Font,
        fontSize: CGFloat,
        color: Color,
        iosTextStyle: String,
        shouldScale: Bool,
        lineHeight: CGFloat,
        letterSpacing: CGFloat
    ) {
        self.font = font
        self.fontSize = fontSize
        self.color = color
        self.iosTextStyle = iosTextStyle
        self.shouldScale = shouldScale
        self.lineHeight = lineHeight
        self.letterSpacing = letterSpacing
    }
}

extension Typograph: ReflectedCustomStringConvertible {
    public override var description: String {
        return reflectedDescription
    }
}
