// This file was generated with Diez - https://diez.org
// Do not edit this file directly.

import DiezModule from './index.js';
export const File = DiezModule.File;
export const Size2D = DiezModule.Size2D;
export const Image = DiezModule.Image;
export const Lottie = DiezModule.Lottie;
export const Font = DiezModule.Font;
export const Color = DiezModule.Color;
export const Typograph = DiezModule.Typograph;
export const GradientStop = DiezModule.GradientStop;
export const Point2D = DiezModule.Point2D;
export const LinearGradient = DiezModule.LinearGradient;
export const DropShadow = DiezModule.DropShadow;
export const Fill = DiezModule.Fill;
export const Panel = DiezModule.Panel;
export const Bindings = DiezModule.Bindings;
export const Diez = DiezModule.Diez;
export default DiezModule;
