# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'HelloMyStateBag' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HelloMyStateBag
  pod 'lottie-ios'
  
  pod 'Diez', :path => './Diez'

  target 'HelloMyStateBagTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
