// This file was generated with Diez - https://diez.org
// Do not edit this file directly.

import Foundation

extension Bundle {
    func url(forFile file: File) -> URL? {
        return url(forResource: file.src.removingPercentEncoding, withExtension: nil)
    }
}
