// This file was generated with Diez - https://diez.org
// Do not edit this file directly.

import Foundation
import CoreGraphics

extension Point2D {
    @objc
    public var cgPoint: CGPoint {
        return CGPoint(x: x, y: y)
    }
}
