// This file was generated with Diez - https://diez.org
// Do not edit this file directly.

import Foundation
import CoreGraphics

extension Size2D {
    @objc
    public var cgSize: CGSize {
        return CGSize(width: width, height: height)
    }
}
