// This file was generated with Diez - https://diez.org
// Do not edit this file directly.

package org.diez.stdlibTestStub

data class DropShadow(
    val offset: Point2D,
    val radius: Float,
    val color: Color
) {
    companion object {}
}
