// This file was generated with Diez - https://diez.org
// Do not edit this file directly.

package org.diez.stdlibTestStub

data class Fill(
    val color: Color,
    val linearGradient: LinearGradient,
    val type: String
) {
    companion object {}
}
