// This file was generated with Diez - https://diez.org
// Do not edit this file directly.

package org.diez.stdlibTestStub

data class Font(
    val file: File,
    val name: String
) {
    companion object {}
}
