// This file was generated with Diez - https://diez.org
// Do not edit this file directly.

package org.diez.stdlibTestStub

data class GradientStop(
    val position: Float,
    val color: Color
) {
    companion object {}
}
