// This file was generated with Diez - https://diez.org
// Do not edit this file directly.

package org.diez.stdlibTestStub

data class Point2D(
    val x: Float,
    val y: Float
) {
    companion object {}
}
