// This file was generated with Diez - https://diez.org
// Do not edit this file directly.

package org.diez.stdlibTestStub

data class Size2D(
    val width: Float,
    val height: Float
) {
    companion object {}
}
