#!/usr/bin/env node
const { comment } = require('@diez/cli-core');
const { fork } = require('child_process');
const { join, resolve } = require('path');

const cwd = resolve(__dirname, '..');

const start = fork('./scripts/start', ['web'], { stdio: 'inherit' });

start.once('message', () => {
  comment(`
Starting example web project...`);
  const devServer = fork(
    './node_modules/.bin/webpack-dev-server',
    [],
    { cwd: join(cwd, 'examples', 'web'), stdio: 'inherit' },
  );
});
