#!/usr/bin/env node
const { canRunCommand, fatalError, info } = require('@diez/cli-core');
const { execSync } = require('child_process');
const { join, resolve } = require('path');

(async () => {
  // Make sure Yarn is installed.
  if (!await canRunCommand('yarn --version')) {
    fatalError('Yarn is required to run the Web example project. See https://yarnpkg.org for details.');
  }

  const cwd = resolve(__dirname, '..');

  info('Building Diez project for Web...');
  execSync('./node_modules/.bin/diez compile -t web', { cwd, stdio: 'inherit' });
  info('Installing Node dependencies...');
  execSync('yarn', { cwd: join(cwd, 'examples', 'web'), stdio: 'inherit' });
  info('Starting the Diez hot server...');
  execSync('./node_modules/.bin/diez hot -t web', { cwd, stdio: 'inherit' });
})();
