// This file was generated with Diez - https://diez.org
// Do not edit this file directly.

import Foundation

extension Bundle {
    static let diezResources = Bundle(url: Bundle.diez.resourceURL!.appendingPathComponent("Static.bundle"))
}
