#!/usr/bin/env node
const { canRunCommand, Format, Log } = require('@diez/cli-core');
const { execSync, fork } = require('child_process');
const { join, resolve } = require('path');

(async () => {
  // Make sure Yarn is installed.
  if (!await canRunCommand('yarn --version')) {
    Log.error('Yarn is required to run the example projects. See https://yarnpkg.org for details.');
    process.exit(1);
  }

  const target = process.argv.pop();
  if (!['android', 'ios', 'web'].includes(target)) {
    Log.error('Usage: start <android|ios|web>');
    process.exit(0);
  }

  if (target === 'ios' && !await canRunCommand('pod --version')) {
    Log.error('CocoaPods is required to run the iOS example project. See installation options:');
    Log.error('https://guides.cocoapods.org/using/getting-started.html#getting-started');
    process.exit(1);
  }

  const cwd = resolve(__dirname, '..');
  const diez = join('.', 'node_modules', '.bin', 'diez');

  Log.comment(`Building Diez project for target ${target}...`);
  let hotProcess;
  let guideUrl;
  switch (target) {
    case 'android':
      execSync(`${diez} compile -t android`, { cwd, stdio: 'inherit' });
      Log.comment('Starting the Diez hot server...');
      hotProcess = fork(diez, ['hot', '-t', 'android'], { cwd, stdio: 'inherit' });
      guideUrl = 'https://beta.diez.org/getting-started/kotlin.html';
      break;
    case 'ios':
      execSync(`${diez} compile -t ios --cocoapods`, { cwd, stdio: 'inherit' });
      Log.comment('Installing CocoaPods dependencies in example codebase...');
      execSync('pod install', { cwd: join(cwd, 'examples', 'ios'), stdio: 'inherit' });
      Log.comment('Starting the Diez hot server...');
      hotProcess = fork(diez, ['hot', '-t', 'ios'], { cwd, stdio: 'inherit' });
      guideUrl = 'https://beta.diez.org/getting-started/swift.html';
      break;
    case 'web':
      execSync(`${diez} compile -t web`, { cwd, stdio: 'inherit' });
      Log.comment('Installing Node dependencies in example codebase...');
      execSync('yarn', { cwd: join(cwd, 'examples', 'web'), stdio: 'inherit' });
      Log.comment('Starting the Diez hot server...');
      hotProcess = fork(diez, ['hot', '-t', 'web'], { cwd, stdio: 'inherit' });
      guideUrl = 'https://beta.diez.org/getting-started/javascript.html';
      break;
  }

  const handleBuilt = (message) => {
    if (message === 'built') {
      hotProcess.off('message', handleBuilt);
      Log.comment(`
Your Diez project is now running in hot mode for ${target}.`);
      Log.comment(`
In hot mode, Diez observes and emits changes to your design system in real time.`);
      if (process.send) {
        process.send('built');
        return;
      }

      Log.comment(`
To see Diez in action, leave the hot server running, open a new tab in your
terminal, and follow along with the guide at:

  ${Format.code(guideUrl)}
`);
    }
  };
  hotProcess.on('message', handleBuilt);
})();
